### ISSUE TITLE
Bug: Player not found after its death

### ISSUE THREAD

**Issue by AureliaDolo** [AureliaDolo/Bomberman#2]
Player 0 was killed by player 0!
thread 'main' panicked at 'Player not found', src/main.rs:162:39
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ee5d8d37baaf5b5a81a98396952839c73ae41c68/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/ee5d8d37baaf5b5a81a98396952839c73ae41c68/library/core/src/panicking.rs:110:14
   2: core::panicking::panic_display
             at /rustc/ee5d8d37baaf5b5a81a98396952839c73ae41c68/library/core/src/panicking.rs:65:5
   3: core::panicking::panic_str
             at /rustc/ee5d8d37baaf5b5a81a98396952839c73ae41c68/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/ee5d8d37baaf5b5a81a98396952839c73ae41c68/library/core/src/option.rs:1817:5
   5: core::option::Option<T>::expect
             at /rustc/ee5d8d37baaf5b5a81a98396952839c73ae41c68/library/core/src/option.rs:692:21
   6: bonberman::State::get_player
             at ./src/main.rs:162:10
   7: bonberman::State::player_update
             at ./src/main.rs:231:22
   8: <bonberman::State as ggez::event::EventHandler>::update
             at ./src/main.rs:328:13
   9: ggez::event::run::{{closure}}
             at /home/aurelia/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.7.0/src/event.rs:312:33
  10: winit::platform_impl::platform::sticky_exit_callback
             at /home/aurelia/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/mod.rs:746:5
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/aurelia/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/x11/mod.rs:290:17
  12: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/aurelia/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/x11/mod.rs:385:9
  13: winit::platform_impl::platform::EventLoop<T>::run
             at /home/aurelia/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/mod.rs:662:56
  14: winit::event_loop::EventLoop<T>::run
             at /home/aurelia/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/event_loop.rs:154:9
  15: ggez::event::run
             at /home/aurelia/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.7.0/src/event.rs:190:5
  16: bonberman::main
             at ./src/main.rs:89:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/ee5d8d37baaf5b5a81a98396952839c73ae41c68/library/core/src/ops/function

**Comment by AureliaDolo** [comment]
seems to happen when player 0 is killed first
